// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeCell } from "./CodeCell";
import type { LLMPromptCell } from "./LLMPromptCell";
import type { TemplateCell } from "./TemplateCell";
import type { WebserviceCell } from "./WebserviceCell";

export type CellTypes = { "Code": CodeCell } | { "Prompt": LLMPromptCell } | { "Web": WebserviceCell } | { "Template": TemplateCell };