// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportedModelProviders } from "./SupportedModelProviders";

export type LLMPromptCell = { "Chat": { path: string | null, provider: SupportedModelProviders, req: string, } } | { "Completion": { req: string, } } | { "Embedding": { req: string, } };