// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportedMemoryProviders } from "./SupportedMemoryProviders";

export interface MemoryCell { provider: SupportedMemoryProviders, function_invocation: string | null, }