// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionCall } from "./FunctionCall";
import type { MessageRole } from "./MessageRole";

export interface TemplateMessage { role: MessageRole, content: string, name: string | null, function_call: FunctionCall | null, }