
name: release

on:
  workflow_dispatch:
  push:
    # Enable when testing release infrastructure on a branch.
     branches:
      - colton/improved-examples-and-releases
    tags:
      - "v.*"
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
      env:
        # Set to force version number, e.g., when no tag exists.
        ARTIFACT_VERSION: TEST-0.0.0
    steps:
      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Get the release version from the tag
        if: env.ARTIFACT_VERSION == ''
        run: |
          echo "ARTIFACT_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.ARTIFACT_VERSION }}"

      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.ARTIFACT_VERSION }}
          name: ${{ env.ARTIFACT_VERSION }}
          allowUpdates: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save release upload URL to artifact
        run: echo "${{ steps.release.outputs.upload_url }}" > artifacts/release-upload-url

      - name: Save version number to artifact
        run: echo "${{ env.ARTIFACT_VERSION }}" > artifacts/release-version

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
