
name: Create GitHub Release

on:
  workflow_dispatch:
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Set release version
        if: env.ARTIFACT_VERSION == ''
        run: python3 ../scripts/get_target_version.py

      - name: Create GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.ARTIFACT_VERSION }}
          name: ${{ env.ARTIFACT_VERSION }}
          allowUpdates: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save release upload URL to artifact
        run: echo "${{ steps.release.outputs.upload_url }}" > artifacts/release-upload-url

      - name: Save version number to artifact
        run: echo "${{ env.ARTIFACT_VERSION }}" > artifacts/release-version

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts
